[workspace]
default-members = ["hypertext", "hypertext-macros"]
members = ["hypertext", "hypertext-macros"]
resolver = "2"

    [workspace.package]
    authors = ["Vidhan Bhatt <me@vidhan.io>"]
    categories = ["template-engine"]
    description = "A blazing fast type-checked HTML macro crate."
    edition = "2024"
    homepage = "https://github.com/vidhanio/hypertext"
    keywords = ["html", "macro"]
    license = "MIT"
    readme = "README.md"
    repository = "https://github.com/vidhanio/hypertext"
    version = "0.6.4"


    [workspace.dependencies]
    hypertext-macros = { version = "0.6", path = "./hypertext-macros" }

    html-escape = { version = "0.2", default-features = false }

    [workspace.lints]
        [workspace.lints.rust]
        missing_copy_implementations = "warn"
        missing_debug_implementations = "warn"
        missing_docs = "warn"
        unsafe_code = "forbid"

        [workspace.lints.clippy]
        cargo = { level = "warn", priority = -1 }
        nursery = { level = "warn", priority = -1 }
        pedantic = { level = "warn", priority = -1 }
        too_long_first_doc_paragraph = "allow"
