root = "."
tmp_dir = "tmp"

[build]
bin = "../../target/debug/htmx-rsx"
cmd = "cargo build"
delay = 1000
exclude_dir = ["node_modules", "target"]
include_dir = ["src"]
include_ext = ["rs"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[misc]
clean_on_exit = false

[proxy]
app_port = 3000
enabled = true
proxy_port = 3001

[screen]
clear_on_rebuild = false
