[package]
name = "htmx-rsx"
edition = "2024"
build = "build.rs"

[dependencies]
axum = "0.8.4"
axum-htmx = "0.7.0"
hypertext = { path = "../../hypertext", features = ["axum", "htmx"] }
tokio = { version = "1.44.2", features = ["full"] }
tower-http = { version = "0.6.2", features = ["fs"] }
